// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post struct {
	ID              string `json:"id"`
	Title           string `json:"title"`
	Description     string `json:"description"`
	PublicationDate int    `json:"publicationDate"`
}

type PostInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}
